name: Go

on:
  push:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build cmd/main.go
        mkdir build/bin
        mv main build/bin/takeover

    - name: Docker
      run: docker build -t willdockerhub/takeover build/
