name: Publish

on:
  push:
    branches:
      - '*'
env:
  DOCKERHUB_USERNAME: willdockerhub

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Login docker registry
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
        
    - name: Build
      run:
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/takeover cmd/main.go

    - name: Docker
      run: docker build -t willdockerhub/takeover build/
 
    - name: Publish
      run: docker push willdockerhub/takeover
