name: Publish

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run:
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/takeover cmd/main.go

    - name: Docker
      run: docker build -t willdockerhub/takeover build/
 
    - name: Publish
      run: docker push willdockerhub/takeover
